# Site settings
title: ahui132
name: ahui132
email: 
description: ''
baseurl: ""
url: "http://hilojack.com"
username: ahui132 

# Build settings
markdown: kramdown
paginate: 10 
paginate_path: "/p:num"
permalink: /p/:title
